#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
  # shellcheck disable=SC2034  # part of the shared wizard-template palette; unused by this wizard's stages
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — macOS code signing + notarization for ess_comprestimator.
#
# Produces the 5 secrets .github/workflows/build.yml already reads
# (APPLE_CERTIFICATE, APPLE_CERTIFICATE_PASSWORD, APPLE_TEAM_ID, APPLE_ID,
# APPLE_APP_SPECIFIC_PASSWORD). Nothing in the workflow needs to change —
# it degrades to unsigned builds today because these aren't set yet.
#
# These values are CI-only (no local build step reads them), so nothing is
# written to .env — only GitHub secrets are set, and only in memory here.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO="cdmaestas/ess_comprestimator"

banner "macOS code signing + notarization setup"

# ── Stage 1 — prerequisite check ───────────────────────────────────────────
stage "Apple Developer Program enrollment"
say "This wizard sets up signing for Individual enrollment (\$99/yr) —"
say "not Organization. If you're on Organization, the cert step differs."
open_url "https://developer.apple.com/account"
step "Confirm your membership shows as Active on the account page."
if ! confirm "Is your Apple Developer Program (Individual) membership active?"; then
  warn "Enroll first at https://developer.apple.com/programs/enroll/ — it can"
  warn "take up to 48h to activate. Re-run this wizard once it's active."
  exit 0
fi

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't installed or authenticated — this wizard needs it to set"
  warn "GitHub secrets at the end. Run 'gh auth login' first, then re-run."
  exit 1
fi

# ── Stage 2 — create the Developer ID Application certificate ─────────────
stage "Create the Developer ID Application certificate"
if command -v xcode-select >/dev/null 2>&1 && xcode-select -p >/dev/null 2>&1 && [[ -d "$(xcode-select -p)/../Applications/Xcode.app" || -e /Applications/Xcode.app ]]; then
  say "Xcode is installed — this is the easier path."
  step "Open Xcode → Settings (⌘,) → Accounts."
  step "Select your Apple ID / team, click 'Manage Certificates…'."
  step "Click the '+' in the bottom-left corner → 'Developer ID Application'."
  step "Xcode creates the certificate and installs it in your login keychain."
else
  note "Xcode not detected — using the manual Certificate Signing Request path."
  step "Open Keychain Access → menu Keychain Access → Certificate Assistant"
  step "  → Request a Certificate From a Certificate Authority…"
  step "Fill in your email, leave CA email blank, select 'Saved to disk', save the .certSigningRequest."
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Choose 'Developer ID' → 'Developer ID Application', upload the .certSigningRequest."
  step "Download the resulting .cer file and double-click it to install into your login keychain."
fi
pause "Done? Press Enter once the certificate shows up in Keychain Access (My Certificates, under 'login')."

# ── Stage 3 — Team ID ───────────────────────────────────────────────────────
stage "Find your Team ID"
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Copy the 'Team ID' shown on the Membership details card (10 characters, e.g. 'A1B2C3D4E5')."
while true; do
  ask APPLE_TEAM_ID "Paste your Team ID:"
  if [[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
    break
  fi
  warn "That doesn't look like a 10-character Team ID (letters/digits only) — try again."
done

# ── Stage 4 — export the certificate as .p12 ────────────────────────────────
stage "Export the certificate as a .p12"
say "This turns the certificate + its private key into one file CI can import."
step "Open Keychain Access → 'My Certificates' (left sidebar, under 'login')."
step "Find the certificate named 'Developer ID Application: <your name> ($APPLE_TEAM_ID)'."
step "Right-click it → Export… → File Format: Personal Information Exchange (.p12)."
step "Save it somewhere findable, e.g. ~/Desktop/comprestimator-signing.p12."
step "You'll be prompted for an export password — pick one now, you'll need it below."
pause "Done exporting? Press Enter to continue."

while true; do
  ask APPLE_P12_PATH "Full path to the exported .p12 file:"
  APPLE_P12_PATH="${APPLE_P12_PATH/#\~/$HOME}"
  if [[ -f "$APPLE_P12_PATH" ]]; then
    break
  fi
  warn "No file found at '$APPLE_P12_PATH' — check the path and try again."
done
ask_secret APPLE_CERTIFICATE_PASSWORD "Export password you just chose:"

note "Encoding the .p12 as base64 (this is what CI actually imports)…"
APPLE_CERTIFICATE=$(base64 -i "$APPLE_P12_PATH" | tr -d '\n')
if [[ -z "$APPLE_CERTIFICATE" ]]; then
  warn "base64 encoding produced nothing — check the file isn't empty."
  exit 1
fi
note "Encoded (${#APPLE_CERTIFICATE} chars) — not printed, it's the signing secret."

# ── Stage 5 — Apple ID + app-specific password (for notarization) ──────────
stage "App-specific password for notarization"
say "notarytool needs an app-specific password, not your real Apple ID password."
open_url "https://appleid.apple.com/account/manage"
step "Sign in → 'Sign-In and Security' → 'App-Specific Passwords' → '+'."
step "Name it something like 'ess_comprestimator CI', then copy the generated password."
ask APPLE_ID "Your Apple ID email (used for notarization):"
ask_secret APPLE_APP_SPECIFIC_PASSWORD "Paste the app-specific password:"

# ── Stage 6 — write the 5 GitHub secrets ────────────────────────────────────
stage "Write GitHub Actions secrets"
say "Setting 5 repo secrets on $REPO. Values are piped to gh, never echoed"
say "or written to disk."
set_secret APPLE_CERTIFICATE "$APPLE_CERTIFICATE"
set_secret APPLE_CERTIFICATE_PASSWORD "$APPLE_CERTIFICATE_PASSWORD"
set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"

note "Verifying (names only — gh secret list never shows values):"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list --repo "$REPO" 2>/dev/null | sed 's/^/  /' || true
fi

note "The exported .p12 at $APPLE_P12_PATH is no longer needed — delete it"
note "once you've confirmed the secrets above are set."
# ──────────────────────────────────────────────────────────────────────────

finish

say "Next: push a tag (git tag vX.Y.Z && git push origin vX.Y.Z), or re-run"
say "the Build workflow — .github/workflows/build.yml will now sign and"
say "notarize the macOS build automatically."
